# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CEE3D8
background         #111212
cursor             #7F9E8F

active_tab_foreground     #111212
active_tab_background     #CEE3D8
inactive_tab_foreground   #CEE3D8
inactive_tab_background   #111212

active_border_color   #CEE3D8
inactive_border_color #111212
bell_border_color     #1A3127

color0      #393A3A
color1		#1A3127
color2		#234234
color3		#234235
color4		#527F67
color5		#57846C
color6		#57846C
color7		#B1CFBF
color8		#7C9186
color9		#234134
color10		#2F5846
color11		#2F5846
color12		#6EA98A
color13		#74B090
color14		#74B090
color15		#B1CFBF
