# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ACEBC7
background         #23292A
cursor             #588E7F

active_tab_foreground     #23292A
active_tab_background     #ACEBC7
inactive_tab_foreground   #ACEBC7
inactive_tab_background   #23292A

active_border_color   #ACEBC7
inactive_border_color #23292A
bell_border_color     #022128

color0      #484E50
color1		#022128
color2		#022529
color3		#03412E
color4		#056133
color5		#126686
color6		#0E9447
color7		#81DAA7
color8		#5A9875
color9		#032C36
color10		#033137
color11		#05563D
color12		#068144
color13		#1888B2
color14		#13C55F
color15		#81DAA7
